### ISSUE TITLE
Handling of indirect descriptor violates virtio spec

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/vm-memory#119]
According to Virtio spec 1.1,  2.6.5.3.2 Device Requirements: Indirect Descriptors:
_The device MUST ignore the write-only flag (flags&VIRTQ_DESC_F_WRITE) in the descriptor that refers
to an indirect table.
The device MUST handle the case of zero or more normal chained descriptors followed by a single descriptor
with flags&VIRTQ_DESC_F_INDIRECT
Note: While unusual (most implementations either create a chain solely using non-indirect descriptors, or
use a single indirect element), such a layout is valid._

And commit "a83152da14554cf810f672f6f4079e943fe6ce28 : simplify descriptor chain handling" breaks the rules defined above.

**Comment by alexandruag** [comment]
HI Gerry! As far as I can tell, the implementation there does follow the rules. Can you please provide a bit more details about what is broken specifically? Also, should we move this issue to the `vm-virtio` repo? :D

**Comment by jiangliu** [comment]
> HI Gerry! As far as I can tell, the implementation there does follow the rules. Can you please provide a bit more details about what is broken specifically? Also, should we move this issue to the `vm-virtio` repo? :D

My bad, it should be open for the vm-virtio crate:(

**Comment by jiangliu** [comment]
Moved to https://github.com/rust-vmm/vm-virtio/issues/28
