### ISSUE TITLE
v0.5.0 release

### ISSUE THREAD

**Issue by elmarco** [rust-vmm/vm-memory#129]
Hi,

Although there are few changes, releasing vm-memory early would allow to merge https://github.com/rust-vmm/vm-virtio/pull/33.

Thanks

**Comment by jiangliu** [comment]
Great, we have dependency on publishing vm-virtio and vhost.

**Comment by elmarco** [comment]
@andreeaflorescu ping? (happy new year!)

**Comment by andreeaflorescu** [comment]
> @andreeaflorescu ping? (happy new year!)

Happy new year!

Can one of the crate maintainers please do a release? CC: @alexandruag @jiangliu @bonzini

**Comment by alexandruag** [comment]
Waiting just a bit more to see if/what other PRs can be merged before this release.

**Comment by jiangliu** [comment]
maybe the hugetlb_fs PR:)

**Comment by andreeaflorescu** [comment]
Published v0.5.0: https://crates.io/crates/vm-memory/0.5.0

Thanks everyone!
