### ISSUE TITLE
MmapError doesn't impl std::error::Error

### ISSUE THREAD

**Issue by joshtriplett** [rust-vmm/vm-memory#17]
Using `?` on `GuestMemoryMmap::new` and similar, in a function returning a generic Error, doesn't work, because `GuestMemoryMmap::new` returns a Result with an error type of `MmapError`, and `MmapError` doesn't impl `std::error::Error`.

Fixing this would allow cleaning up many uses of `.unwrap()`.

**Comment by andreeaflorescu** [comment]
Should we close this one or is there anything else required here?
CC: @bonzini @jiangliu

**Comment by joshtriplett** [comment]
LGTM, thank you.
