### ISSUE TITLE
volatile_memory::Error doesn't impl std::error::Error

### ISSUE THREAD

**Issue by joshtriplett** [rust-vmm/vm-memory#18]
Using `?` on `VolatileMemory::get_slice` (applied to a `MmapRegion`), in a function returning a generic Error, doesn't work, because `VolatileMemory::get_slice` returns a Result with an error type of `volatile_memory::Error`, which doesn't impl `std::error::Error`.

Fixing this would make it easier to avoid using `.unwrap()`.

**Comment by fkuchar** [comment]
Is anybody working on this? (and #17 )
It looks like a good first issue so I'd like to take a stab at it.

**Comment by jiangliu** [comment]
welcome, no one works on these two issues yet:)
