### ISSUE TITLE
MmapRegion::build fails when the backing object is a device

### ISSUE THREAD

**Issue by slp** [rust-vmm/vm-memory#195]
Currently `mmap::check_file_offset` attempts to validate the backing object by checking, among other things, its size to confirm the mapping will fit on it. This check is implemented by using `std::fs::metadata` to obtain the file size, but this approach doesn't work when the backing object is a block or char device, as the returned value is always zero.

This was discovered when [virtiofsd](https://gitlab.com/virtio-fs/virtiofsd) users noticed that adding a memory object in QEMU backed by a device (i.e. `/dev/kvmfr0`) would cause the daemon to fail with `Waiting for daemon failed: HandleRequest(ReqHandlerError(Custom { kind: Other, error: MappingPastEof }))` ([issue 46](https://gitlab.com/virtio-fs/virtiofsd/-/issues/46)).

**Comment by GZibrat** [comment]
Thanks for putting in a fix! However, I don't think this fixes the issue entirely. For example, running fstat on a vfio device returns 0 for the size which makes virtiofsd return MmapRegion(MappingPastEof).

Is there a reason in particular this check is needed at all? mmap will verify all of this and return failure if any condition is not met.

**Comment by roypat** [comment]
> Thanks for putting in a fix! However, I don't think this fixes the issue entirely. For example, running fstat on a vfio device returns 0 for the size which makes virtiofsd return MmapRegion(MappingPastEof).

Just to clarify - the PR that closed this issue was replacing fstat with seek exactly to avoid issues like this where fstat returns a size of zero. Are you saying that there's devices where neither seek nor fstat return anything meaningful?

> Is there a reason in particular this check is needed at all? mmap will verify all of this and return failure if any condition is not met.

I was thinking the same the other day admittedly. I don't think this check has too much value. I tried patching over some other rough edges it has in #320, but I'd also be happy to accept a PR that eliminates `check_file_offset` altogether.

**Comment by GZibrat** [comment]
> Just to clarify - the PR that closed this issue was replacing fstat with seek exactly to avoid issues like this where fstat returns a size of zero. Are you saying that there's devices where neither seek nor fstat return anything meaningful?

Sorry! I got confused by the order of things here. But yes, vfio devices do not support seek or stat (returns 0 size). I tried the seek implementation that is in now, this [commit](https://github.com/rust-vmm/vm-memory/pull/320/commits/cbced4a2c833d9da029986c494f3e335169d3dec), and a simple c program that calls fstat. None seemed to provide a valid size.

**Comment by roypat** [comment]
> > Just to clarify - the PR that closed this issue was replacing fstat with seek exactly to avoid issues like this where fstat returns a size of zero. Are you saying that there's devices where neither seek nor fstat return anything meaningful?
> 
> Sorry! I got confused by the order of things here. But yes, vfio devices do not support seek or stat (returns 0 size). I tried the seek implementation that is in now, this [commit](https://github.com/rust-vmm/vm-memory/pull/320/commits/cbced4a2c833d9da029986c494f3e335169d3dec), and a simple c program that calls fstat. None seemed to provide a valid size.

Awesome, thanks for this piece of info! Let me rework #320 to just drop this entire check altogether then
