### ISSUE TITLE
New release request: 0.8.1

### ISSUE THREAD

**Issue by vireshk** [rust-vmm/vm-memory#201]
Are there any plans to make a new release for vm-memory crate ? We need [this commit](https://github.com/rust-vmm/vm-memory/commit/f06ac79677548faf725095386de2a953f2a5ac70), via [crates.io](http://crates.io/), for our Xen virtio development.

**Comment by andreeaflorescu** [comment]
We can draft a release. I think we can get #200 in as well since it's a small one.

**Comment by lauralt** [comment]
Opened https://github.com/rust-vmm/vm-memory/pull/202 for the release.
