### ISSUE TITLE
Unsoundness: VolatileMemory should be `unsafe`, private, or sealed because it relies on get_slice in unsafe code

### ISSUE THREAD

**Issue by Manishearth** [rust-vmm/vm-memory#250]
https://github.com/rust-vmm/vm-memory/blob/06ebc2a36e1df29923887cb32a829ad6ea243634/src/volatile_memory.rs#L110-L112

The behavior of this trait method is relied upon in multiple places in unsafe code, e.g:

https://github.com/rust-vmm/vm-memory/blob/06ebc2a36e1df29923887cb32a829ad6ea243634/src/volatile_memory.rs#L122-L123

A user of this library implementing `VolatileMemory` could cause unsoundness by writing an incorrect implementation of `VolatileMemory::get_slice()`. This means that it should be an `unsafe trait` (or private/sealed) with the safety requirements for implementors documented on the trait.

**Comment by roypat** [comment]
Thank you for bringing your security concerns to our attention! We will investigate these immediately and follow up with you within 5 business days to provide a status.

If you have any further questions or concerns, please do not hesitate to contact us according to the [rust-vmm security disclosure policy](https://github.com/rust-vmm/community/blob/main/SECURITY.md).

Thanks again!

**Comment by roypat** [comment]
Hello @Manishearth, 
we have fixed the issue in #251 and published vm-memory 0.12.2 to crates.io. We will also go through the process of filing a RustSec advisory for affected versions. Thank you again for reporting this issue!
