### ISSUE TITLE
Crate does not build on nightly

### ISSUE THREAD

**Issue by 00xc** [rust-vmm/vm-memory#263]
The following currently fails:

```
$ cargo +nightly build
```

This is also causing a build failure for dependent crates (e.g. [vm-virtio](/rust-vmm/vm-virtio)):
https://docs.rs/crate/virtio-queue/0.10.0/builds/961806

Which also prevents docs from being built:
https://docs.rs/crate/virtio-queue/0.10.0

**Comment by roypat** [comment]
Hi, please make sure that you are running the latest nightly to rule out https://github.com/rust-vmm/vm-memory/issues/261 as the root cause here. If you still see it with todays nightly, please post the compilation error you are seeing.

**Comment by rbradford** [comment]
Closing, thanks!
