### ISSUE TITLE
`MmapRange` under `xen` feature flag

### ISSUE THREAD

**Issue by jarkkojs** [rust-vmm/vm-memory#289]
For me this API looks like one we could move in [Enarx](https://enarx.dev/) but what puzzles is me is that why it is under Xen flag. Just sanity checking that it is usable without any connection to Xen.

**Comment by jarkkojs** [comment]
I wonder also why this is not working:

```
// SPDX-License-Identifier: MIT
//! Copyright (c) Jarkko Sakkinen 2024

use vm_memory::{GuestAddress, MmapRange, MmapRegion};

const ADDRESS: u64 = 0;
const SIZE: usize = 0x3000;
const PROT: i32 = libc::PROT_READ | libc::PROT_WRITE;

fn main() {
    let mut range = MmapRange::new(SIZE, None, GuestAddress(ADDRESS), 0, 0);    
    range.set_prot(PROT);
    let region = MmapRegion::<()>::from_range(range).unwrap_or_else(|e| {
        eprintln!("{e}");
        std::process::exit(1);
    });
    println!("{:?}", region);
}
```

This results:

```
Bad file descriptor (os error 9)
```

So even for anonymous mapping one has to open `/dev/null` and not just pass null?

**Comment by bonzini** [comment]
I think you're looking at mmap_xen instead of mmap_unix.

**Comment by jarkkojs** [comment]
> I think you're looking at mmap_xen instead of mmap_unix. You need to disable the xen feature and enable the unix feature.

Hmm... so this is what I'm seeing:

```
   Avaliable features for `vm-memory`
default = []
backend-atomic = ["arc-swap"]
backend-bitmap = []
backend-mmap = []
xen = ["backend-mmap", "bitflags", "vmm-sys-util"]
arc-swap (optional)
bitflags (optional)
vmm-sys-util (optional)
```

`xen` was the only thing that made `MmapRange` after trial and error. What I'm doing wrong here?

**Comment by jarkkojs** [comment]
For reference compilation lock with `backend-mmap` and without `xen`:

```bash
❯ cargo b
   Compiling hello-vm-memory v0.1.0 (/home/jarkko/work/local/hello-vm-memory)
error[E0432]: unresolved import `vm_memory::MmapRange`
  --> src/main.rs:7:31
   |
7  | use vm_memory::{GuestAddress, MmapRange, MmapRegion};
   |                               ^^^^^^^^^ no `MmapRange` in the root
   |
note: found an item that was configured out
  --> /home/jarkko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vm-memory-0.14.1/src/lib.rs:66:16
   |
66 | pub use mmap::{MmapRange, MmapXenFlags};
   |                ^^^^^^^^^

error[E0599]: no function or associated item named `from_range` found for struct `vm_memory::MmapRegion` in the current scope
   --> src/main.rs:16:36
    |
16  |     let region = MmapRegion::<()>::from_range(range).unwrap_or_else(|e| {
    |                                    ^^^^^^^^^^ function or associated item not found in `MmapRegion`
    |
note: if you're trying to build a new `vm_memory::MmapRegion` consider using one of the following associated functions:
      vm_memory::MmapRegion::<B>::new
      vm_memory::MmapRegion::<B>::from_file
      vm_memory::MmapRegion::<B>::build
      vm_memory::MmapRegion::<B>::build_raw
   --> /home/jarkko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vm-memory-0.14.1/src/mmap_unix.rs:247:5
    |
247 |       pub fn new(size: usize) -> Result<Self> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
260 |       pub fn from_file(file_offset: FileOffset, size: usize) -> Result<Self> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
278 | /     pub fn build(
279 | |         file_offset: Option<FileOffset>,
280 | |         size: usize,
281 | |         prot: i32,
282 | |         flags: i32,
283 | |     ) -> Result<Self> {
    | |_____________________^
...
310 |       pub unsafe fn build_raw(addr: *mut u8, size: usize, prot: i32, flags: i32) -> Result<Self> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `hello-vm-memory` (bin "hello-vm-memory") due to 2 previous errors
```

**Comment by jarkkojs** [comment]
> For reference compilation lock with `backend-mmap` and without `xen`:
> 
> ```shell
> ❯ cargo b
>    Compiling hello-vm-memory v0.1.0 (/home/jarkko/work/local/hello-vm-memory)
> error[E0432]: unresolved import `vm_memory::MmapRange`
>   --> src/main.rs:7:31
>    |
> 7  | use vm_memory::{GuestAddress, MmapRange, MmapRegion};
>    |                               ^^^^^^^^^ no `MmapRange` in the root
>    |
> note: found an item that was configured out
>   --> /home/jarkko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vm-memory-0.14.1/src/lib.rs:66:16
>    |
> 66 | pub use mmap::{MmapRange, MmapXenFlags};
>    |                ^^^^^^^^^
> 
> error[E0599]: no function or associated item named `from_range` found for struct `vm_memory::MmapRegion` in the current scope
>    --> src/main.rs:16:36
>     |
> 16  |     let region = MmapRegion::<()>::from_range(range).unwrap_or_else(|e| {
>     |                                    ^^^^^^^^^^ function or associated item not found in `MmapRegion`
>     |
> note: if you're trying to build a new `vm_memory::MmapRegion` consider using one of the following associated functions:
>       vm_memory::MmapRegion::<B>::new
>       vm_memory::MmapRegion::<B>::from_file
>       vm_memory::MmapRegion::<B>::build
>       vm_memory::MmapRegion::<B>::build_raw
>    --> /home/jarkko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vm-memory-0.14.1/src/mmap_unix.rs:247:5
>     |
> 247 |       pub fn new(size: usize) -> Result<Self> {
>     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ...
> 260 |       pub fn from_file(file_offset: FileOffset, size: usize) -> Result<Self> {
>     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ...
> 278 | /     pub fn build(
> 279 | |         file_offset: Option<FileOffset>,
> 280 | |         size: usize,
> 281 | |         prot: i32,
> 282 | |         flags: i32,
> 283 | |     ) -> Result<Self> {
>     | |_____________________^
> ...
> 310 |       pub unsafe fn build_raw(addr: *mut u8, size: usize, prot: i32, flags: i32) -> Result<Self> {
>     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> Some errors have detailed explanations: E0432, E0599.
> For more information about an error, try `rustc --explain E0432`.
> error: could not compile `hello-vm-memory` (bin "hello-vm-memory") due to 2 previous errors
> ```

Managed to get a working example: 

```rust
// SPDX-License-Identifier: MIT
//! Copyright (c) Jarkko Sakkinen 2024

#![deny(clippy::all)]
#![deny(clippy::pedantic)]

use vm_memory::MmapRegion;

const SIZE: usize = 0x3000;
const PROT: i32 = libc::PROT_READ | libc::PROT_WRITE | libc::PROT_EXEC;

fn main() {
    let region = unsafe { MmapRegion::<()>::build_raw(std::ptr::null_mut(), SIZE, PROT, 0) }
        .unwrap_or_else(|e| {
            eprintln!("{e}");
            std::process::exit(1);
        });
    println!("{region:?}");
}
```

Only thing I'm missing now here is that

1. Why XEN API is so heavily different than UNIX API? To me this looks in ubiquitous sense some what messy.
2. How should I deal with with unsafe property of `build_raw()`.

**Comment by jarkkojs** [comment]
Looking at help it shows completely different API, i.e. the Xen API: https://docs.rs/vm-memory/latest/vm_memory/mmap/struct.MmapRegion.html

Feels confusing to me...

**Comment by jarkkojs** [comment]
I guess this might be a better option for me https://docs.rs/memmap2/latest/memmap2/. I.e. less detached from VMM context :-)
