### ISSUE TITLE
Allow adding GuestRegionMmap's to GuestMemoryMmap

### ISSUE THREAD

**Issue by dagrh** [rust-vmm/vm-memory#3]
GuestMemoryMmap only has a:
  pub fn new(ranges: &[(GuestAddress, usize)]) -> std::result::Result<Self, MmapError> {

constructor.
We need a way to build a GuestMemoryMmap that's full of GuestRegionMmap's (e.g. that are created from_fd's).
So either a new constructor or an 'insert' method.

**Comment by dagrh** [comment]
I've got the following which I think is OK, might need some more checks:

[PATCH] GuestMemoryMap: from_regions

Add a method to take a vector of MmapRegion's that already exist and
turn them into a GuestMemoryMap.

Signed-off-by: Dr. David Alan Gilbert <dgilbert@redhat.com>
---
 src/mmap.rs | 22 ++++++++++++++++++++++
 1 file changed, 22 insertions(+)

diff --git a/src/mmap.rs b/src/mmap.rs
index 236867b..1cefd81 100644
--- a/src/mmap.rs
+++ b/src/mmap.rs
@@ -349,6 +349,28 @@ impl GuestMemoryMmap {
             regions: Arc::new(regions),
         })
     }
+
+    pub fn from_regions(ranges: Vec<GuestRegionMmap>) -> std::result::Result<Self, MmapError> {
+        if ranges.is_empty() {
+            return Err(MmapError::NoMemoryRegion);
+        }
+
+        for rangei in 1..ranges.len() {
+            let range = &ranges[rangei];
+            let last = &ranges[rangei - 1];
+            if last
+                .guest_base
+                .checked_add(last.mapping.len() as GuestAddressValue)
+                .map_or(true, |a| a > range.min_addr())
+            {
+                return Err(MmapError::MemoryRegionOverlap);
+            }
+        }
+
+        Ok(Self {
+            regions: Arc::new(ranges),
+        })
+    }
 }
 
 impl GuestMemory for GuestMemoryMmap {
-- 
2.20.1

**Comment by dagrh** [comment]
[0001-GuestMemoryMap-from_regions.patch.txt](https://github.com/rust-vmm/vm-memory/files/2997732/0001-GuestMemoryMap-from_regions.patch.txt)

**Comment by jiangliu** [comment]
Fixed by https://github.com/rust-vmm/vm-memory/pull/5
