### ISSUE TITLE
Cleanup after moving to Rust 1.34

### ISSUE THREAD

**Issue by alexandruag** [rust-vmm/vm-memory#30]
After #19 gets merged, looks like we'll have an extra `Cargo.toml` feature (`integer-atomics`) and an extra dependency (`cast`) because of missing Rust features that got added/stabilized in `1.34`. We should remove these as soon as we can assume everyone uses `1.34` or a newer version.

**Comment by andreeaflorescu** [comment]
Since Rust 1.39 was released can we assume that everyone uses something > 1.34 so that we can get rid of the cast dependency?

**Comment by bonzini** [comment]
See rust-vmm/community#84.

**Comment by bonzini** [comment]
The `integer-atomics` feature probably should not be removed until `target_has_atomic` is stabilized (rust-lang/rust#32976), even though the atomics _are_ available on the platforms we target.
