### ISSUE TITLE
The trait ReadVolatile and WriteVolatile are not implemented for TcpStream

### ISSUE THREAD

**Issue by ljrcore** [rust-vmm/vm-memory#303]
Hello,

I'm currently working on a project that requires handling both TCP sockets (TcpStream) and Unix domain sockets (UnixStream) using the vm-memory crate. I've encountered a challenge due to the difference in trait implementations between these two types of sockets.

In vm-memory, the ReadVolatile and WriteVolatile traits are implemented for UnixStream, but not for TcpStream. This discrepancy poses a problem when trying to write generic functions that can handle both socket types without code duplication.

# Problem Details

- Use Case

I have functions that need to perform volatile read and write operations over sockets. These functions are generic and accept a socket parameter. The operations inside the functions require the socket to implement ReadVolatile and WriteVolatile.

- Challenge with TcpStream

Since TcpStream does not implement ReadVolatile and WriteVolatile, I cannot pass a TcpStream to these functions without encountering a compilation error.

- Code Duplication Concern

Splitting the functions into separate implementations for TcpStream and UnixStream leads to significant code redundancy, which I want to avoid.

# Attempted Solutions

- Removing WriteVolatile Constraint

If I remove the WriteVolatile bound, the function accepts TcpStream, but then I cannot perform the volatile write operations needed with UnixStream.

- Using Trait Objects or Enums

I've considered using trait objects or enums to abstract over the socket types, but this introduces complexity and may impact performance.

# Request for Guidance

- Implementation in vm-memory

Would it be appropriate to implement ReadVolatile and WriteVolatile for TcpStream within vm-memory?

- Alternative Approaches

Are there alternative patterns or recommended practices within the vm-memory ecosystem to handle this scenario effectively?

I appreciate any guidance or insights you can provide on this issue. Thank you for your time and for maintaining such a helpful crate.

**Comment by ljrcore** [comment]
> Good morning! Yes, implementing `ReadVolatile` and `WriteVolatile` for `TcpStream` is definitely appropriate! If I'm not mistaken, it should be a simple matter of adding `impl_read_volatile_for_raw_fd!(std::net::TcpStream);` in io.rs, around here: https://github.com/rust-vmm/vm-memory/blob/main/src/io.rs#L147 :)

It should be `impl_read_write_volatile_for_raw_fd!(std::net::TcpStream);` instead of `impl_read_volatile_for_raw_fd!(std::net::TcpStream);`.

Now it works. I will submit this enhancement, thanks.

**Comment by roypat** [comment]
> > Good morning! Yes, implementing `ReadVolatile` and `WriteVolatile` for `TcpStream` is definitely appropriate! If I'm not mistaken, it should be a simple matter of adding `impl_read_volatile_for_raw_fd!(std::net::TcpStream);` in io.rs, around here: https://github.com/rust-vmm/vm-memory/blob/main/src/io.rs#L147 :)
> 
> It should be `impl_read_write_volatile_for_raw_fd!(std::net::TcpStream);` instead of `impl_read_volatile_for_raw_fd!(std::net::TcpStream);`.
> 
> Now it works. I will submit this enhancement and add your `Suggested-by`. Thanks.

argh, right. Misread the macro name, sorry!
