### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by alexandruag** [rust-vmm/vm-memory#31]
As we merge the remaining PRs, and the code base appears to settle down, we should start thinking about publishing `vm-memory` on `crates.io` (or identify any reasons to hold back and for how long). One semantic versioning question is whether we want to bump the version to `1.0.0` first, or we're fine with staying at `0.something` for the time being.

Let's track any work/concerns related to publishing on this issue. From our side, I'm currently working towards merging #29 and going through another full code review of the crate to make sure things look fine for the upcoming Firecracker integration.

**Comment by andreeaflorescu** [comment]
For kvm-ioctls and kvm-bindings the first version published on crates.io was 0.1.0. I think we should keep the same version for now. Whoever takes care of publishing on crates.io, please take a look at the list of requirements published in the [community readme](https://github.com/rust-vmm/community#publishing-on-cratesio---requirements-list) to make sure we keep the same quality standard across all rust-vmm crates.

**Comment by jiangliu** [comment]
We should get #27, #28, #29 merged before publishing the crate to crates.io.

**Comment by andreeaflorescu** [comment]
There are a few more things required:
- We should also have high level documentation and examples. I took a look at the documentation using `cargo doc --open` and it looks a bit incomplete.
- Coverage test (for this one I think it might be better to first merged the rust-vmm-ci PR and switch to that one instead of duplicating the code again)

**Comment by andreeaflorescu** [comment]
I think we also need a better example in the README.md. I honestly don't really understand the current examples (https://github.com/rust-vmm/vm-memory#example). We can use the same example in both src/lib.rs and README.md as one of them is showing up on crates.io and the other one in docs.rs

**Comment by sboeuf** [comment]
Just reviving this thread! What is still missing, preventing us from publishing on crates.io?
#27 is still opened, and @andreeaflorescu mentioned about cleaning up the examples. Is that it?
And who wants to take care of this?

**Comment by jiangliu** [comment]
> Just reviving this thread! What is still missing, preventing us from publishing on crates.io?
> #27 is still opened, and @andreeaflorescu mentioned about cleaning up the examples. Is that it?
> And who wants to take care of this?

There's no reply from @tkreuzer , so the PR #27 is still pending:(

**Comment by jiangliu** [comment]
Also #23 should also be covered too. The tempfile PR is going to be merged into vmm-sys-util, so we could resume #23 .

**Comment by Trolldemorted** [comment]
>There's no reply from @tkreuzer , so the PR #27 is still pending:(

For how long will you continue to wait?

**Comment by jiangliu** [comment]
> > There's no reply from @tkreuzer , so the PR #27 is still pending:(
> 
> For how long will you continue to wait?

I feel it's right time to publish the vm-memory crate now, many other crates have dependencies on it.

**Comment by andreeaflorescu** [comment]
@jiangliu we still have a few PRs pending. We want to add some more documentation. This shouldn't take too long though. Are you okay with 2 more weeks?

**Comment by jiangliu** [comment]
> @jiangliu we still have a few PRs pending. We want to add some more documentation. This shouldn't take too long though. Are you okay with 2 more weeks?

That's absolutely ok, we are on Chinese New Year holiday, which is about one week:)

**Comment by andreeaflorescu** [comment]
> > @jiangliu we still have a few PRs pending. We want to add some more documentation. This shouldn't take too long though. Are you okay with 2 more weeks?
> 
> That's absolutely ok, we are on Chinese New Year holiday, which is about one week:)

Happy holidays! Let's sync again afterwards.

**Comment by serban300** [comment]
I posted a PR containing some small adjustments for the documentation: #69 . @bonzini @jiangliu @alexandruag can you take a look please ?

Also I would be happy to contribute if there's anything else that's needed in order to publish the crate.

**Comment by bonzini** [comment]
I would like to merge at least the first patch in #68, because it changes the public API by splitting a trait in two. No other objection from me.

**Comment by bonzini** [comment]
#68 is no longer a blocker since we have gotten rid of `GuestMemoryMut`.

**Comment by serban300** [comment]
@alexandruag @bonzini @jiangliu @andreeaflorescu 

Since there are no more blockers here, I just wanted to check if there is any plan to publish the crate in the near future.

**Comment by serban300** [comment]
> @alexandruag @bonzini @jiangliu @andreeaflorescu
> 
> Since there are no more blockers here, I just wanted to check if there is any plan to publish the crate in the near future.

Sorry, just a quick ping related to this.

We would like to use this crate in Firecracker, but we would strongly prefer to consume it from crates.io .

Would everyone be comfortable with publishing this crate as it is now ? Are there any other issues that need to be sorted out ?

I'm not sure what the publishing process consists of, but I would be happy to help if there's anything I can do.

**Comment by andreeaflorescu** [comment]
Let's publish it!

I can do that, it's rather easy. You need to have write permissions on the repository, do a `cargo publish` and then add the gatekeepers as the owners of the crate: `cargo owner --add github:rust-vmm:gatekeepers`

Ping @bonzini. Are you also okay with publishing it now?

**Comment by bonzini** [comment]
Yes, of course! Sorry I missed that you were waiting for me.

**Comment by andreeaflorescu** [comment]
Welp, the crate manifest is not correct so we can't publish it :laughing: 

I'll submit a PR to fix it and then publish it to crates.io.

**Comment by andreeaflorescu** [comment]
PR: https://github.com/rust-vmm/vm-memory/pull/78

**Comment by andreeaflorescu** [comment]
Published: https://crates.io/crates/vm-memory

It looks a bit ugly on the front page. I will make some adjustments, but for that I will open a new issue.
