### ISSUE TITLE
Improve performance of GuestMemoryMmap::find_region()

### ISSUE THREAD

**Issue by rbradford** [rust-vmm/vm-memory#41]
This function gets called a lot and appears in the performance reports when running cloud-hypervisor.

This currently has an O(n) algorithm and a simple fix I think would be to keep the vector of regions sorted and then use `Vec::binary_search_by` to give us an O(lg n) lookup. The added cost of sorting the regions when new ones get added would be minimal compared to the number of times `.find_region()` is called

**Comment by rbradford** [comment]
cc @sboeuf @sameo

**Comment by jiangliu** [comment]
Just curious, what scenarios make the find_region() as a hotspot?

**Comment by bonzini** [comment]
I agree. The number of regions is usually small, but if there was a cut-off size below which binary search loses, it should be implemented in `Vec::binary_search_by`.

**Comment by rbradford** [comment]
It appears in `perf top` traces when running under high network load. This because the the virtio-net code makes a lot of use of functionality to look into guest memory.

**Comment by jiangliu** [comment]
Any plan to implement some cache policy into the find_region() hot path?

**Comment by bonzini** [comment]
No plans to add caching, but the original issue with O(n) performance is fixed. Should this be closed? Or is `find_region()` still on the profiles?

**Comment by jiangliu** [comment]
So let's close it first. We may open another if other performance hotspot appears later.
