### ISSUE TITLE
Add constructors to mmap_unix

### ISSUE THREAD

**Issue by sboeuf** [rust-vmm/vm-memory#74]
It'd be useful to add a global constructor to `MmapRegion` in `mmap_unix.rs` ([here](https://github.com/rust-vmm/vm-memory/blob/master/src/mmap_unix.rs#L91)) since this would provide a proper wrapper for the `mmap()` syscall.

The point would be to be able to provide `PROT_NONE/READ/WRITE` along with `MAP_SHARED/PRIVATE/...`, so that we're not tied to the predefined prototype and map types.

**Comment by sboeuf** [comment]
@bonzini @jiangliu @alexandruag wdyt?

**Comment by jiangliu** [comment]
> @bonzini @jiangliu @alexandruag wdyt?

We have used the build() constructor to create mmap region for virtio-fs:)

**Comment by sboeuf** [comment]
Oh my bad, I didn't even see the `build()` constructor...
