### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-memory#86]
Can we add a changelog to this repository? It helps in keeping track of changes between releases.

Can we also tag the commit from which you publish to crates.io so that people can easily identify the code version starting from the crates.io version? This is what we've done for the other crates that are published as well. I can do that if the maintainers are on board with this.

CC: @bonzini @alexandruag @jiangliu

**Comment by bonzini** [comment]
Agree on both counts, thanks!
