### ISSUE TITLE
Add struct_util module from linux-loader

### ISSUE THREAD

**Issue by aghecenco** [rust-vmm/vm-memory#88]
See also https://github.com/rust-vmm/linux-loader/issues/20, https://github.com/rust-vmm/linux-loader/pull/23#discussion_r390287530

[`struct_util`](https://github.com/rust-vmm/linux-loader/blob/master/src/loader/struct_util.rs) is a generic utility module that reads structs from bytes. It should be included in this utility crate and consumed by `linux-loader` from here.

**Comment by andreeaflorescu** [comment]
Transferred this issue from vmm-sys-util to vm-memory as the implementation is in vm-memory now.

Fix introduced in: https://github.com/rust-vmm/vm-memory/pull/83
